### ISSUE TITLE
[Feature Request] pip package CD

### ISSUE THREAD

**Issue by L04DB4L4NC3R** [GDGVIT/Selenium-Cookie-Injector#10]
### Requirements
GitHub actions is needed on master to publish this package to `pypy` as soon as a PR is merged. Maintainers need to be subsequently notified about the same. 

### Potential notification media
*Any one*
- Telegram
- Mail
- Issue comment

### Additional features
GitHub actions for automatic release build with the `GIT_SHA` of the latest commit as version prefix.[This](https://github.com/c4milo/github-release) might help with the releases.

**Comment by SphericalKat** [comment]
I'm leaning in favour of telegram for notifications, lemme know what you prefer.

**Comment by L04DB4L4NC3R** [comment]
> I'm leaning in favour of telegram for notifications, lemme know what you prefer.

All in for telegram. We can add the bot to a maintainers' group.
