### ISSUE TITLE
Add a production logger 

### ISSUE THREAD

**Issue by Geek-ubaid** [GDGVIT/Selenium-Cookie-Injector#19]
Add a logger instead of using print commands in. You can take reference from here: https://realpython.com/python-logging/

**Comment by searchformyusername** [comment]
@Geek-ubaid Print command are used in tests.py when error is thrown.
Will add logging for whole

**Comment by Geek-ubaid** [comment]
No it's used in the main wrapper function for exception handling you have used print statements.
@D-E-F-E-A-T

**Comment by L04DB4L4NC3R** [comment]
@D-E-F-E-A-T use a logger with with JSON output and with the following levels:

* info
* warn
* error

You can log to a file if `level=error`, but this is up to you.

**Comment by searchformyusername** [comment]
@L04DB4L4NC3R Why with JSON output?

**Comment by L04DB4L4NC3R** [comment]
Because then everyone will be able to integrate it in their own log pipeline. JSON is the standard for logging in such pipelines. Whatever library you use will have JSON logging support.

**Comment by searchformyusername** [comment]
https://github.com/GDGVIT/Selenium-Cookie-Injector/pull/20#issue-365328731
@Geek-ubaid @L04DB4L4NC3R

**Comment by L04DB4L4NC3R** [comment]
Merged #20
