### ISSUE TITLE
Remove *.pyc files from master

### ISSUE THREAD

**Issue by L04DB4L4NC3R** [GDGVIT/Selenium-Cookie-Injector#4]
### Issue description
`__pycache__` was pushed to master. Remove it, and only then solve #3. Add `*.pyc` and `__pycache__` to `.gitignore`

**Comment by searchformyusername** [comment]
solved

**Comment by L04DB4L4NC3R** [comment]
Reference the commit here @D-E-F-E-A-T

**Comment by searchformyusername** [comment]
https://github.com/GDGVIT/Selenium-Cookie-Injector/pull/6/commits/804a99ffefd06e8fabdfef837ac02dd84e0bbfb8
@L04DB4L4NC3R

**Comment by L04DB4L4NC3R** [comment]
`.gitignore` required for not pushing any caches in the future, @D-E-F-E-A-T

**Comment by D-E-F-E-A-T** [comment]
@L04DB4L4NC3R Yes. So I make changes in it ?

**Comment by searchformyusername** [comment]
@L04DB4L4NC3R 
Done
Commit: f4ad8fb5e8587ef6863f0183404b02171013e4b2

**Comment by L04DB4L4NC3R** [comment]
Approved #7
