### ISSUE TITLE
Fix the directory structure of the package

### ISSUE THREAD

**Issue by Geek-ubaid** [GDGVIT/Selenium-Cookie-Injector#5]
Rectify the following mistakes in the dir structure of the package:

- [x] Add dist folder to the gitignore file
- [x] make a test folder in your main folder Seleniumcookie

The package dir structure can be like this:
```bash 
SeleniumCookie
     tests
            __init__.py
            test.py
     __init__.py
     cookie_injector.py
     wrapper.py
```

**Comment by searchformyusername** [comment]
Issue Resolved
