### ISSUE TITLE
SeleniumCookie giving permission error in windows

### ISSUE THREAD

**Issue by Geek-ubaid** [GDGVIT/Selenium-Cookie-Injector#8]
Procedure Followed by me:
-  installed SeleniumCookie in an environment using pip

-  Wrote the test script given in the readme:

![image](https://user-images.githubusercontent.com/31818185/72681962-a69a9f00-3aee-11ea-840c-60a280c41d7f.png)

Output:
![image](https://user-images.githubusercontent.com/31818185/72681944-6cc99880-3aee-11ea-91e9-902106aab159.png)

Check this issue as it might come in other system as well. The issue is arising at the removal of tempfile using os.remove().

**Comment by L04DB4L4NC3R** [comment]
@Geek-ubaid I guess it's a mutex lock on the file `tmp_cookie_file`. It's acquired by either a running program, or the win system

**Comment by L04DB4L4NC3R** [comment]
This is most likely due to the file not being closed after a recent write, @D-E-F-E-A-T

**Comment by D-E-F-E-A-T** [comment]
will check it in windows, If found this error is coming to me also then will remove complete window support.

**Comment by searchformyusername** [comment]
@L04DB4L4NC3R Ok I see incase after last minor changes something went wrong.

**Comment by searchformyusername** [comment]
@Geek-ubaid @L04DB4L4NC3R working in linux(ubuntu:eoan). Just Checked. Will test on windows by midnight.

**Comment by L04DB4L4NC3R** [comment]
@D-E-F-E-A-T How is #9 related to this issue?

**Comment by searchformyusername** [comment]
@L04DB4L4NC3R [This was the issue](https://stackoverflow.com/questions/46133223/maximum-value-of-timestamp/47291926)

**Comment by L04DB4L4NC3R** [comment]
> @L04DB4L4NC3R [This was the issue](https://stackoverflow.com/questions/46133223/maximum-value-of-timestamp/47291926)

I see. The expiration exception was ignored by the system and caused a problem later on. Would have been easier to debug if it had been caught. **Catch and handle all exceptions**.

@D-E-F-E-A-T mention a *time expiration constant* rather than explicitly passing the value. 

```python
MAX_EXPIRATION=32536799999000000
offset = min(int(item[3]), MAX_EXPIRATION)
```
Then publish the package.

**Comment by D-E-F-E-A-T** [comment]
@L04DB4L4NC3R OKAY :cry:

**Comment by D-E-F-E-A-T** [comment]
@L04DB4L4NC3R Label can be changed to improvement instead of bug.

**Comment by L04DB4L4NC3R** [comment]
> @L04DB4L4NC3R Label can be changed to improvement instead of bug.

It was a bug on windows, and its resolution is yet to be tested by @Geek-ubaid

**Comment by Geek-ubaid** [comment]
# SeleniumCookie Package Test Result

Ran the script for the whatsapp login using the package SeleniumCookies==0.3(test Release) .

### System Config:
- Windows 10
- Chrome Browser

### Python Config
- Python(3.6.8)

![image](https://user-images.githubusercontent.com/31818185/72756308-cadfa400-3bf2-11ea-8871-cf373936f2cc.png)

The package succesfully added cookies to my browser and i can see the saved cookies at chrome://settings/siteData.

The issue mentioned above no longer exists now

**Comment by Geek-ubaid** [comment]
The major release of the package is here [v0.4](https://github.com/GDGVIT/Selenium-Cookie-Injector/releases/tag/v0.4)
